on:
  push:
    tags:
      - 'v*'
name: Create release and build binaries
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: 'Release Notes and changelog'
          draft: true 
          prerelease: false
  armv7_job:
    runs-on: [self-hosted, Linux, ARM]
    name: Build armv7l 
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm run fetch-libsodium
      - run: npm install
      - run: npm run prebuild
      - run: tar --create --verbose --file="${{ github.tag }}-linux-armv7l.tar" --directory "./prebuilds" .
      - name: Upload build
        uses: johnwbyrd/update-release@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./${{ github.ref }}-linux-armv7l.tar
  aarch64_job:
    runs-on: [self-hosted, Linux, ARM64]
    name: Build aarch64 
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm run fetch-libsodium
      - run: npm install
      - run: npm run prebuild
      - run: tar --create --verbose --file="${{ github.ref }}-linux-armv7l.tar" --directory "./prebuilds" .
      - name: Upload build
        uses: johnwbyrd/update-release@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./${{ github.ref }}-linux-aarch64.tar
